# Generated by Django 4.1.7 on 2024-01-24 07:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kitob nomi')),
                ('author', models.CharField(max_length=255, verbose_name='Kitob muallifi')),
                ('genre', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255, verbose_name='Kitob rasmi')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=60)),
                ('chat_id', models.IntegerField()),
                ('phone_number', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', "So'ralgan"), ('accepted', 'Qabul qilingan'), ('rejected', 'Rad etilgan'), ('completed', 'Tugallangan')], max_length=10, verbose_name='Almashuv statusi')),
                ('borrowed_date', models.DateTimeField(auto_now_add=True, verbose_name='Kitobni olgan sana')),
                ('return_date', models.DateTimeField(default=datetime.datetime(2024, 2, 3, 12, 21, 20, 136802), editable=False, verbose_name='Kitobni qaytarish muddati')),
                ('provision', models.CharField(choices=[('self', "O'zim yetkazaman"), ('post', 'Pochtadan yuboraman'), ('pickup', "O'zingiz kelib olib ketasiz")], max_length=6)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.book', verbose_name='Almashilgan kitob')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.telegramuser', verbose_name='Kitobni olgan foydalanuvchi')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userbooks', to='robot.telegramuser', verbose_name='Kitobning egasi'),
        ),
    ]
