# Generated by Django 4.1.7 on 2024-01-24 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0003_alter_status_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 12, 22, 56, 13295), editable=False, verbose_name='Kitobni qaytarish muddati'),
        ),
    ]
