# Generated by Django 4.1.7 on 2024-01-27 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0005_alter_status_return_date_alter_telegramuser_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 20, 0, 42, 654988), editable=False, verbose_name='Kitobni qaytarish muddati'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('requested', "So'ralgan"), ('accepted', 'Qabul qilingan'), ('rejected', 'Rad etilgan'), ('completed', 'Tugallangan')], default='requested', max_length=10, verbose_name='Almashuv statusi'),
        ),
    ]
