# Generated by Django 4.1.7 on 2024-01-27 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0006_alter_status_return_date_alter_status_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='provision',
            field=models.CharField(choices=[('self', "O'zim yetkazaman"), ('post', 'Pochtadan yuboraman'), ('pickup', "O'zingiz kelib olib ketasiz")], default=None, max_length=6),
        ),
        migrations.AlterField(
            model_name='status',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 20, 19, 29, 795186), editable=False, verbose_name='Kitobni qaytarish muddati'),
        ),
    ]
