# Generated by Django 4.1.7 on 2024-01-28 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0008_alter_status_return_date_alter_telegramuser_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 7, 10, 55, 4, 960793), editable=False, verbose_name='Kitobni qaytarish muddati'),
        ),
    ]
