# Generated by Django 4.1.7 on 2024-01-29 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0014_alter_status_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 23, 40, 38, 647857, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Kitobni qaytarish muddati'),
        ),
    ]
